### ISSUE TITLE
Unknown error on Server Side Rendering with local contentaCMS

### ISSUE THREAD

**Issue by imfaber** [contentacms/contenta_vue_nuxt#32]
Hello, first of all thanks for this project because I'm learning a lot about Vue.js and Nuxt.js.

I'm experiencing an unknown error on SSR when I run contenta_jsonapi locally.
Now, I'm not sure whether the issue is with the consumer or with the server as if I use the public APIs (https://live-contentacms.pantheonsite.io/api) it actually works, so my apologies in advance if I'm posting to the wrong repo.

Anyway, the issue I'm having is only on SSR because after the first page load, which redirects me to /server-unreachable, if I navigate to the home, recipes etc.. using the router links it is all good.

I tried to log what the waterwheel calls are returning and here is what I get:

`error findAllLatestRecipes { Error: Unknown error.
    at /Users/imfaber/Sites/imfaber-v3/node_modules/waterwheel/dist/waterwheel.js:1:5194
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) message: 'Unknown error.', status: 500 }`

Has anyone experienced the same by any chance?

I thought about posting this here first because, unless I'm missing something, I can't find anything wrong on the server side, CORS is fine, API endpoints are fine etc... 

Many thanks.

**Comment by imfaber** [comment]
Sorry, after further investigation it came out the error was [Error: getaddrinfo ENOTFOUND] due to Node.js not being able to connect to my localhost.

All working fine after updating my hosts file.
