### ISSUE TITLE
✖ error Error: certificate has expired

### ISSUE THREAD

**Issue by ShaunWMusic** [contentacms/contenta_vue_nuxt#54]
Site does not load locally. 

✖ error Error: certificate has expired
  at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
  at TLSSocket.emit (events.js:189:13)
  at TLSSocket.EventEmitter.emit (domain.js:441:20)
  at TLSSocket._finishInit (_tls_wrap.js:633:8)

**Comment by Al-Rozhkov** [comment]
See #52
